### ISSUE TITLE
Having lunar date on a single line and parashah book name with references

### ISSUE THREAD

**Issue by TupiniViking** [Ordisoftware/Hebrew-Calendar#1222]
It would be really nice if we could choose the Layout of the day.

From changing the font with size and format to the type and amount of information.

It would be nice to be able to add notes on each day and have the option to display.

Today the information you have is.

[Day on the Gregorian calendar]
A: Sunrise Time ' Name of the Month [month number] #Number of the day of the month in the Hebrew calendar
S: Sunset time

In the year 2022 Gregorian month of October 22nd the Calendar looks like this for the City of "Jundaí" in Brazil where I am.

27
R:05:26 'Heshvan[8]#3
S:18:18

I would like to change this Layout to something like this.

27 - [Month:8 - Heshavan - Day 3]
R - 05:26' / S - 18:18'
Parshah Week 2:
• Torah Sefer Bereshit / Genesis 6.9 - 11.32
• Parashah #2 : Noah / נח
Notes:
• Is 54:1-55:5, Mt 3:1-4:25

Or another option of the user's choice.
With the option to print in PDF not as an image but as a drawing.

Options for language editing would make it much better.

People from all over the world could contribute.

I speak Portuguese and a little English.
My wife English and Spanish.

Many could help with the translation if they have the option.

Another option is to have the Hebrew Calendar as the primary and the Gregorian Calendar as the secondary.

**Comment by Ordisoftware** [comment]
Thanks for all these good suggestions!

- I note choosing a layout for the day for a future version but at first only to choose the order of the items currently displayed in this order: moon or sun times depending on the chosen omer, Torah celebration, equinox or solstice, and parashah name. For example, one may prefer to have the parashah name before the season change event.

- I also note an option to display the time of the sun and the moon at the same time for those who have enough space on the screen, and an option to choose the order (sun, moon) or (moon, sun). Another option is also possible without difficulty to have the Hebrew date on a single line and choose the position.

- Having the Hebrew date, day and month, instead of the Gregorian can be complex and the control code is in [Calendar.cs](https://github.com/Ordisoftware/Hebrew-Calendar/blob/main/Project/Dependencies/Calendar.NET/Calendar.cs) that I adapted years after years.

- Font type for the visual month may be a choice too as for the tabular text view.

- Font size can be changed in preferences:

    ![image](https://user-images.githubusercontent.com/22332878/198423782-50d29b7e-c68a-408d-a355-a17aee6eb15b.png)

- The Hebrew date format can be changed in the same way:

    ![image](https://user-images.githubusercontent.com/22332878/198424053-fc4926f3-42c9-4b5a-8759-73f2124cf0be.png)

    To match your wish you can set: `[Month:%MONTHNUM% - %MONTHNAME% - Day %DAYNUM%]` but I see there is capitalization in the code and it's an error I got already corrected for the next version scheduled to be released in a few days.

    ![image](https://user-images.githubusercontent.com/22332878/198428285-5299c2ab-f7f4-499d-b047-a30f2e9da38d.png)

- An advanced layout as suggested can be implemented using a more complex algorithm using templates for the entire display, but I can't guarantee I'll have the time right now. The concerned file (not yet refactored as expected) is [MainForm.FillMonths.cs](https://github.com/Ordisoftware/Hebrew-Calendar/blob/main/Project/Source/Forms/MainForm/Data/MainForm.FillMonths.cs).

- To print in PDF: not planned for Calendar but the monthly view can be exported as an image that can be converted with any suitable software, or placed in a word document to be saved in PDF format. Creating a PDF using the raw drawing is beyond my skills and my time. The image export module is in the file [MainForm.Export.Save.cs](https://github.com/Ordisoftware/Hebrew-Calendar/blob/main/Project/Source/Forms/MainForm/Export/MainForm.Export.Save.cs) (also need to be refactored).

- A Portuguese translation can be added as exposed in https://github.com/Ordisoftware/Hebrew-Calendar/issues/852. As indicated, a refactoring of the translation system to use external text files that anybody can translate by hand is not yet available due to lack of time. True multilingual using a DLL plugin system and an editor is planned for the long term when I have time and after all major planned improvements.

**Comment by Ordisoftware** [comment]
Here are the selected tasks for the version 9.34:

- [ ] Add option to have the Hebrew date on a single line before the ephemeris in the month view.
- [ ] Add option to display hebrew month names in Latin Transcription or in Hebrew Unicode or both.
- [ ] Add option to display celebration names in Latin Transcription or in Hebrew Unicode or both.
- [ ] Add option to display parashah names in Latin Transcription or in Hebrew Unicode or both.
- [ ] Add option to display book names in Latin Transcription or in Hebrew Unicode or both.

Here are the selected tasks for the version 9.35:

- [ ] Add option to display only omer ephemeris or sun and moon the same time in the month view
- [ ] Add option to choose font type in the month view.

Here are the selected tasks for the version 10.0:

- [ ] Add option to choose information order in the month view.
- [ ] Add options to display and format additional parashah information in the month view (book name, references...)

**Comment by Ordisoftware** [comment]
Here is an example of what has been done for the parashah layout (sun omer):

![image](https://user-images.githubusercontent.com/22332878/198505232-6331a194-0f46-4b59-96e5-442b85036a70.png)

**Comment by Ordisoftware** [comment]
This is what a display might look like with an option for Hebrew names in Unicode. It's weird because the days go from left to right and the reading in a box from right to left. I hesitate because even aligned on the left it's weird... So I'm thinking of adding an option and I'll see later if it's possible to generate the entire calendar in mirror but I have doubts it might be complex and I don't know when I will have the time. Or perhaps align right only the parashah data ?

![image](https://user-images.githubusercontent.com/22332878/199219216-903be8fc-e949-441d-957b-0df831132147.png)

![image](https://user-images.githubusercontent.com/22332878/199219512-2286448a-1e85-4521-abc7-2662f422c9bd.png)

![image](https://user-images.githubusercontent.com/22332878/199220677-ab4da8bf-c54e-4099-84d1-f7e9c76db669.png)

**Comment by Ordisoftware** [comment]
Changes are complete for what I thought I could do quickly and I will consider this issue complete in a few days and the next version will be released shortly with the other changes. The settings screen looks like this and it gives two apparently interesting results. Others suggestions has been moved to the associated epic issue for future versions. Thanks again!

![image](https://user-images.githubusercontent.com/22332878/199243623-b81d1055-f91e-497d-bc35-4fda4f08958e.png)

![image](https://user-images.githubusercontent.com/22332878/199243659-4ca43e7a-c1ad-4e1c-bff0-9f758876fa5b.png)

![image](https://user-images.githubusercontent.com/22332878/199243712-7381ecc3-5a85-4268-9950-46f41abd95aa.png)

**Comment by Ordisoftware** [comment]
Epic ans tasks updated.

**Comment by Ordisoftware** [comment]
This is how the settings and display look so far for the first part:

![image](https://user-images.githubusercontent.com/22332878/199654031-6909fc78-8704-41cc-a77a-423f1f582577.png)

![image](https://user-images.githubusercontent.com/22332878/199654036-2c42a17b-3152-4dfc-937b-4b2bbedf38e8.png)

![image](https://user-images.githubusercontent.com/22332878/199654062-955e0fa0-df8d-4db2-81c5-793cd7a117e0.png)

![image](https://user-images.githubusercontent.com/22332878/199654067-365d053d-deeb-4ec8-ba5f-be364a30aa9d.png)
